apiVersion: apps/v1
kind: Deployment
metadata:
  name: zero-downtime-app
spec:
  replicas: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: zero-downtime

  template:
    metadata:
      labels:
        app: zero-downtime
    spec:
      containers:
        - name: app
          image: registry.k8s.io/e2e-test-images/agnhost:2.44
          args:
            - netexec
            - --http-port=8080
            - --http-override=/echo?msg=v1
          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 2

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3